### ISSUE TITLE
performance issues subset.core.create_mask 

### ISSUE THREAD

**Issue by tlogan2000** [roocs/clisops#160] opened 2021-04-01 15:22 UTC
* clisops version: 0.6.1
* Python version: 3.8
* Operating System: linux

### Description
The introduction of `vectorized.touches` into subset.core.create_mask (version v0.5.1) can cause a very large slow down when creating the mask.  This could be linked to the complexity of the polygon but is still somewhat problematic

### What I Did
comparing recent version vs 0.5.0 mask creation for a geojson goes from seconds / instantaneous  to 20 minutes or more.  
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by tlogan2000** [comment] 2021-04-01 15:27
I'd suggest making this optional via a `touches` fllag or similar?   I imagine this cascades into subset_shape and possibly elsewehre as well?

**Comment by Zeitsperre** [comment] 2021-04-01 16:02
I think I've implemented the `touches` flag in the past. I can reintroduce it to the `core` (and can take a stab at `ops`) if we wish. Upstream changes will be desirable/needed in Finch.

**Comment by tlogan2000** [comment] 2021-04-01 16:04
Personal preference would be to have `touches=False` as the default

**Comment by Zeitsperre** [comment] 2021-04-01 16:05
I'll leave `touches=True` for the `ops` side to not break expected behaviour on the ROOCS side of things.

**Comment by tlogan2000** [comment] 2021-04-01 16:05
Seems strange though some other shapefiles/polygons seem to work fine?  I could provide my problem shape if needed

**Comment by Zeitsperre** [comment] 2021-04-01 16:06
Sure. Is it small enough to be shared here?

**Comment by tlogan2000** [comment] 2021-04-01 16:54
````
from clisops.core import subset
import xarray as xr
import geopandas as gpd
import numpy as np
url = 'https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/ouranos/portraits-clim-1.1/NRCAN_obs_tx_days_above_gt_30_annual.nc'
lon_bnds = [-85, -55]
lat_bnds = [44, 65]
r = 'obs'

ds = subset.subset_bbox(xr.open_dataset(url, chunks='auto'),
                                                lon_bnds=lon_bnds, lat_bnds=lat_bnds, start_date='1951')

poly = gpd.GeoDataFrame.from_file('problem_poly.geojson')
mask = subset.create_mask(x_dim=ds.lon, y_dim=ds.lat, poly=poly)
mask
````

**Comment by tlogan2000** [comment] 2021-04-01 16:55
[problem_poly.zip](https://github.com/roocs/clisops/files/6245151/problem_poly.zip)

**Comment by tlogan2000** [comment] 2021-04-01 16:56
Example code and associated geojson uploaded here.   clisops==0.5.0 runs super quickly.  latest version is crazy long?

**Comment by ellesmith88** [comment] 2021-04-12 11:49
I don't think I can be very helpful here as I don't have a lot of experience with polygons etc., but maybe @agstephens will be able to say whether `touches=True` is the best default for the `ops` stuff. For reference the diff where it was added is here https://github.com/roocs/clisops/compare/v0.5.0...v0.5.1

**Comment by tlogan2000** [comment] 2021-06-01 13:11
@aulemahal added you here following yesterday's exchanges

**Comment by aulemahal** [comment] 2021-06-01 21:27
Spend too much time on this, but I came to the following conclusions:

# `PyGEOS`
The "vectorized" code in `shapely` is currently not being developed because most efforts are being put in [pygeos](https://pygeos.readthedocs.io/en/latest/index.html). I was able to get a better version of `create_mask` using tools from there, either directly, or through `geopandas` which uses pygeos when installed. The good thing is, it implements `points.covered_by` which results in the same as `contains or touches`, but is faster. The bad thing is, it is still very slow, I wasn't patient enough to wait for completion.

# `shapely.vectorized`
For some reasons, only the `touches` and `contains` predicates have been implemented in `shapely`, the former being painfully slow even with cython. But the everything is there for the vectorization of the other methods (`covers`, `within`, `covered_by`, etc).  By adding `covers` I was able to bring the computation time down to a very reasonable 18s.

# `dask`
By creating a dask arrays of the points to test, I was able to parallelize by calling `map_blocks`. Easy to implement. I didn't look into `dask-geopandas` yet.

# Cut polygons to bbox and simplify
A few easy steps to reduce the complexity can to be to cut the polygons to the bbox of the data (and vice-versa). Also, simplifying the polygons makes sense by reducing the number of points. 

For now I am opening a PR to shapely with a few of the missing vectorized methods. I am not impressed by PyGEOS, I really thought it would compare to `shapely,vectorized`... May be I am doing something wrong...

**Comment by aulemahal** [comment] 2021-06-02 16:39
As you can now see in my last closing comment on the shapely PR , I clearly did something wrong yesterday. `pygeos` _is_ faster than shapely vectorized. 

Are we interested in implementing a `pygeos`-backed version of `clisops.core.subset`? I would say yes, but it could also stay an optional dependency as the package seems to be still in a development/unstable phase.

@tlogan2000 @ellesmith88 , what do you think? (Trevor is on vacation)

**Comment by tlogan2000** [comment] 2021-06-02 16:59
My impression is that despite pygeos being pretty 'young' or 'new', functions like `intersect` or `contains` will likely be pretty stable.  Exact `pygeos` syntax could change but under the hood they are pretty basic GIS functionalities

**Closed** 2021-06-07 08:14 UTC
Labels: help wanted
